#!/opt/bin/sh

export SSL_CERT_FILE=/opt/etc/ssl/certs/ca-certificates.crt
export HOME=/root
PATH=/opt/bin:/opt/sbin:/usr/sbin:/usr/bin:/sbin:/bin

# =========================
# GENERATED BY VPN PANEL
# =========================

TEST_URL=${test_url}
EXPECTED_TEXT=${expected_text}
TOP_COUNT=${top_count}
TIMEOUT=${timeout}
CONNECT_TIMEOUT=${connect_timeout}
CHECK_RETRIES=${check_retries}
CHECK_RETRY_DELAY=${check_retry_delay}
SWITCH_DELAY=${switch_delay}

LOCK_FILE=${lock_file}
LOG_FILE=${log_file}
GOOD_FILE=${good_file}
TMP_FILE=${tmp_file}
BODY_FILE=${body_file}

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG_FILE"
}

lock() {
  if [ -f "$LOCK_FILE" ]; then
    OLD_PID="$(cat "$LOCK_FILE" 2>/dev/null)"
    if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
      exit 0
    fi
  fi

  echo $$ > "$LOCK_FILE"
  trap 'rm -f "$LOCK_FILE" "$TMP_FILE" "$BODY_FILE"' EXIT
}

check_resource_once() {
  CODE="$(curl -k -L -s \
    --max-time "$TIMEOUT" \
    --connect-timeout "$CONNECT_TIMEOUT" \
    -A 'Mozilla/5.0' \
    -o "$BODY_FILE" \
    -w '%{http_code}' \
    "$TEST_URL" 2>/dev/null)"

  case "$CODE" in
    200|301|302)
      ;;
    *)
      log "HTTP check failed: url=$TEST_URL code=$CODE"
      rm -f "$BODY_FILE"
      return 1
      ;;
  esac

  if grep -q "$EXPECTED_TEXT" "$BODY_FILE"; then
    rm -f "$BODY_FILE"
    return 0
  fi

  log "Content check failed: expected text not found for $TEST_URL"
  rm -f "$BODY_FILE"
  return 1
}

check_resource() {
  ATTEMPT=1
  while [ "$ATTEMPT" -le "$CHECK_RETRIES" ]; do
    if check_resource_once; then
      return 0
    fi

    if [ "$ATTEMPT" -lt "$CHECK_RETRIES" ]; then
      sleep "$CHECK_RETRY_DELAY"
    fi

    ATTEMPT=$((ATTEMPT + 1))
  done

  return 1
}

get_top_locations() {
  adguardvpn-cli list-locations "$TOP_COUNT" 2>/dev/null \
    | sed 's/\r//g' \
    | awk '
      BEGIN { header_found=0 }
      /^ISO[[:space:]]+COUNTRY/ { header_found=1; next }
      /^You can connect/ { exit }
      header_found && NF >= 4 { print $1 }
    '
}

get_current_location() {
  adguardvpn-cli status 2>/dev/null \
    | sed 's/\r//g' \
    | awk -F': ' '
      /Location:/ { print $2; exit }
      /location:/ { print $2; exit }
    '
}

try_location() {
  LOC="$1"
  [ -z "$LOC" ] && return 1

  CURRENT_LOC="$(get_current_location | tr -d '\r')"

  if [ -n "$CURRENT_LOC" ] && [ "$CURRENT_LOC" = "$LOC" ]; then
    log "Skipping location $LOC because it is already current"
  else
    log "Trying location: $LOC"

    adguardvpn-cli disconnect >/dev/null 2>&1
    sleep 3

    adguardvpn-cli connect -l "$LOC" >/dev/null 2>&1
    sleep "$SWITCH_DELAY"
  fi

  if check_resource; then
    log "SUCCESS: resource reachable via $LOC"
    echo "$LOC" > "$GOOD_FILE"
    return 0
  fi

  log "FAILED: resource unreachable via $LOC"
  return 1
}

lock

mkdir -p /opt/tmp
mkdir -p /opt/var/log

if check_resource; then
  log "OK: resource reachable, no switch needed"
  exit 0
fi

log "FAIL: resource unreachable, starting location rotation"

if [ -f "$GOOD_FILE" ]; then
  LAST_GOOD="$(head -n 1 "$GOOD_FILE" | tr -d '\r\n')"
  if [ -n "$LAST_GOOD" ]; then
    log "Trying last known good location: $LAST_GOOD"
    try_location "$LAST_GOOD" && exit 0
  fi
fi

get_top_locations > "$TMP_FILE"

if [ ! -s "$TMP_FILE" ]; then
  log "ERROR: could not get locations list"
  exit 1
fi

while IFS= read -r LOC; do
  [ -z "$LOC" ] && continue

  LAST_GOOD=""
  if [ -f "$GOOD_FILE" ]; then
    LAST_GOOD="$(head -n 1 "$GOOD_FILE" | tr -d '\r\n')"
  fi

  if [ -n "$LAST_GOOD" ] && [ "$LOC" = "$LAST_GOOD" ]; then
    continue
  fi

  try_location "$LOC" && exit 0
done < "$TMP_FILE"

log "Fallback: trying quick connect"
adguardvpn-cli disconnect >/dev/null 2>&1
sleep 3
adguardvpn-cli connect >/dev/null 2>&1
sleep "$SWITCH_DELAY"

if check_resource; then
  log "SUCCESS: resource reachable via quick connect"
  exit 0
fi

log "ERROR: no working location found"
exit 1
