#!/opt/bin/sh

export SSL_CERT_FILE=/opt/etc/ssl/certs/ca-certificates.crt
export HOME=/opt/home/admin
PATH=/opt/bin:/opt/sbin:/usr/sbin:/usr/bin:/sbin:/bin

# =========================
# GENERATED BY VPN PANEL
# Python-native rotation runner
# =========================

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
APP_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
PYTHON_BIN=${python_bin}

cd "$APP_DIR" || exit 1

exec "$PYTHON_BIN" vpn_panel_server.py rotate
